### ISSUE TITLE
The display and link will be corrupted, when the path/file name encoding is not UTF-8.

### ISSUE THREAD

**Issue by n0nel** [websvnphp/websvn#105]
After changing these as follows, it seems to be working good.

comp.php
filedetails.php
log.php

```diff
--- a/comp.php
+++ b/comp.php
@@ -372,6 +372,7 @@
 
 				// Check for a new node entry
 				if (strncmp(trim($line), 'Index: ', 7) == 0) {
+					$line = mb_convert_encoding($line, 'UTF-8', 'auto');
 					// End the current node
 					if ($node) {
 						$listing[$index++]['endpath'] = true;
@@ -393,7 +394,7 @@
 					$listvar = &$listing[$index];
 					$listvar['newpath'] = escape($absnode);
 
-					$listvar['fileurl'] = $config->getURL($rep, $absnode, 'file').'rev='.$rev2;
+					$listvar['fileurl'] = $config->getURL($rep, toOutputEncoding($absnode), 'file').'rev='.$rev2;
 
 					if ($debug) echo 'Creating node '.$node.'<br />';
 
@@ -439,6 +440,7 @@
 
 						$node = $propnode;
 
+						$node = mb_convert_encoding($node, 'UTF-8', 'auto');
 						$listing[$index++]['newpath'] = $node;
 						clearVars();
 					}
```
```diff
--- a/filedetails.php
+++ b/filedetails.php
@@ -108,10 +108,10 @@
 
 	// If a MIME type is associated with the file, deliver with Content-Type header.
 	if ($history && !empty($mimeType) && $rep->hasReadAccess($path, false)) {
-		$base = basename($path);
+		$base = basename(urldecode($path));
 		header('Content-Type: '.$mimeType);
 		//header('Content-Length: '.$size);
-		header('Content-Disposition: inline; filename='.urlencode($base));
+		header('Content-Disposition: inline; filename="'.$base.'"; '."filename*=UTF-8''".rawurlencode($base));
 		$svnrep->getFileContents($path, '', $rev, $peg);
 		exit;
 	}
```
```diff
--- a/log.php
+++ b/log.php
@@ -307,7 +307,7 @@
 				$listvar['revlog'] = nl2br($bugtraq->replaceIDs(create_anchors(xml_entities($revision->msg))));
 				$listvar['rowparity'] = $row;
 
-				$listvar['compareurl'] = $config->getURL($rep, '', 'comp').'compare[]='.$rpath.'@'.($thisrev - 1).'&amp;compare[]='.$rpath.'@'.$thisrev;
+				$listvar['compareurl'] = $config->getURL($rep, '', 'comp').'compare[]='.urlencode($rpath).'@'.($thisrev - 1).'&amp;compare[]='.urlencode($rpath).'@'.$thisrev;
 
 				if ($showchanges) {
 					// Aggregate added/deleted/modified paths for display in table
```

**Comment by ams-tschoening** [comment]
Thanks for reporting those issues. As you already have DIFFs anyway, feel free to instantly open a PR next time, that makes discussing individual changes easier. I have two questions:

> $line = mb_convert_encoding($line, 'UTF-8', 'auto');

What's the environment you are using WebSVN in? From my understanding, those lines come from `svn diff` using some shell and I wonder what's the output of that command under different OS and if all of those are properly supported by `auto`.

> header('Content-Disposition: inline; filename="'.$base.'"; '."filename*=UTF-8''".rawurlencode($base));

Shouldn't this be the UTF-8 name only? I don't think we need to be backwards compatible, I'm not in my own software providing downloads and file names. So I prefer the following to keep things as simple as possible:

> header('Content-Disposition: inline; filename*=UTF-8''.rawurlencode($base));

https://stackoverflow.com/a/6745788/2055163

**Comment by michael-o** [comment]
@ams-tschoening You can provide both parameters for the client to decide, but the patch is wrong. Since  `$base` contains non-ASCII chars, it cannot be set. Either it is stripped down to 7-bit or only UTF-8 filename is retained.

**Comment by n0nel** [comment]
> @ams-tschoening You can provide both parameters for the client to decide, but the patch is wrong. Since `$base` contains non-ASCII chars, it cannot be set. Either it is stripped down to 7-bit or only UTF-8 filename is retained.

Converting the $base with urlencode(rawurlencode) is because I want to download a file with a non-ascii and containing spaces file name.
"filename*=UTF-8" is added to prevent character corruption in IE.
Below is another patch idea.
```php
$base = basename($path);
header('Content-Disposition: inline; filename="'.rawurldecode($base).'"; '."filename*=UTF-8''".rawurlencode($base));
```

**Comment by n0nel** [comment]
> 
> 
> Thanks for reporting those issues. As you already have DIFFs anyway, feel free to instantly open a PR next time, that makes discussing individual changes easier. I have two questions:
> 
> > $line = mb_convert_encoding($line, 'UTF-8', 'auto');
> 
The environment is Windows server 2016.
The character code of the file name handled by Subversion is SJIS (CP932), and the PHP application is UTF-8.
Since files use other encodings, such as EUC, I configure "include/command.php" as follows.
```php
function detectCharacterEncoding($str) {
	$list = array(/*'ASCII',*/ 'UTF-8', 'SJIS', 'JIS', 'EUC-JP', 'ISO-8859-1');
```

**Comment by michael-o** [comment]
> 
> 
> > @ams-tschoening You can provide both parameters for the client to decide, but the patch is wrong. Since `$base` contains non-ASCII chars, it cannot be set. Either it is stripped down to 7-bit or only UTF-8 filename is retained.
> 
> Converting the $base with urlencode(rawurlencode) is because I want to download a file with a non-ascii and containing spaces file name.
> "filename*=UTF-8" is added to prevent character corruption in IE.
> Below is another patch idea.
> 
> ```
> $base = basename($path);
> header('Content-Disposition: inline; filename="'.rawurldecode($base).'"; '."filename*=UTF-8''".rawurlencode($base));
> ```

This looks wrong to be. `$base` is a string with some encoding. When you apply `rawurldecode()` it will give you nothing because `$base` hasn't been encoded before. Does `rawurlencode()` the proper this? This means correct percent-encoded UTF-8 bytes even if the source is not UTF-8?

**Comment by ams-tschoening** [comment]
@n0nel This is going in the wrong direction, please try and say what happens when you use the following line for the header:

    header('Content-Disposition: inline; filename*=UTF-8''.rawurlencode($base));

I was just saying that I only use headers of this format in my own software and things work as expected. We don't need backwards compatible non-UTF-8 support anymore, which is what `filename=` provides.

**Comment by michael-o** [comment]
@ams-tschoening True for browsers, I guess. We can provide filename= when we know that the content is 7-bit ASCII only. Otherwise use the UTF-8 version solely.

**Comment by n0nel** [comment]
I wrote Content-Disposition by referring to the following.
[Use of the Content-Disposition Header Field in the Hypertext Transfer Protocol (HTTP)](https://tools.ietf.org/html/rfc6266#section-5)

**Comment by n0nel** [comment]
I improved the patch. I've tried to make this patch available to everyone, not just me.

- comp.php

```diff
--- a/comp.php
+++ b/comp.php
@@ -378,7 +378,7 @@
 						clearVars();
 					}
 
-					$node = trim($line);
+					$node = trim(toOutputEncoding($line));
 					$node = substr($node, 7);
 					if ($node == '' || $node[0] != '/') $node = '/'.$node;
 
@@ -393,7 +393,7 @@
 					$listvar = &$listing[$index];
 					$listvar['newpath'] = escape($absnode);
 
-					$listvar['fileurl'] = $config->getURL($rep, $absnode, 'file').'rev='.$rev2;
+					$listvar['fileurl'] = $config->getURL($rep, escape($absnode), 'file').'rev='.$rev2;
 
 					if ($debug) echo 'Creating node '.$node.'<br />';
 
@@ -439,7 +439,7 @@
 
 						$node = $propnode;
 
-						$listing[$index++]['newpath'] = $node;
+						$listing[$index++]['newpath'] = escape(toOutputEncoding($node));
 						clearVars();
 					}
 
```

- filedetails.php

```diff
--- a/filedetails.php
+++ b/filedetails.php
@@ -111,7 +111,7 @@
 		$base = basename($path);
 		header('Content-Type: '.$mimeType);
 		//header('Content-Length: '.$size);
-		header('Content-Disposition: inline; filename='.urlencode($base));
+		header('Content-Disposition: inline; filename="'.rawurldecode($base).'"; '."filename*=UTF-8''".rawurlencode($base));
 		$svnrep->getFileContents($path, '', $rev, $peg);
 		exit;
 	}
```

- log.php

```diff
--- a/log.php
+++ b/log.php
@@ -307,7 +307,7 @@
 				$listvar['revlog'] = nl2br($bugtraq->replaceIDs(create_anchors(xml_entities($revision->msg))));
 				$listvar['rowparity'] = $row;
 
-				$listvar['compareurl'] = $config->getURL($rep, '', 'comp').'compare[]='.$rpath.'@'.($thisrev - 1).'&amp;compare[]='.$rpath.'@'.$thisrev;
+				$listvar['compareurl'] = $config->getURL($rep, '', 'comp').'compare[]='.urlencode($rpath).'@'.($thisrev - 1).'&amp;compare[]='.urlencode($rpath).'@'.$thisrev;
 
 				if ($showchanges) {
 					// Aggregate added/deleted/modified paths for display in table
```
