### ISSUE TITLE
The URL in the "Diff" column for directories with non-ASCII characters is too long

### ISSUE THREAD

**Issue by n0nel** [websvnphp/websvn#106]
[View Log] click.
/log.php?repname=_somerep_&path=_somepath_&isdir=1&

And [Show changed files] click
/log.php?repname=_somerep_&path=_somepath_&isdir=1&showchanges=1

Then the link in the "Diff" column should look like this:
/comp.php?repname=_somerep_&compare[]=_somepath_@_revnum1_&compare[]=_somepath_@_revnum2_

However, I found that sometimes the path length were hundreds or thousands of characters long.
I checked and found that if the PATH tag in the xml obtained by running "svn log" splits into 2 lines, the link URL is broken. It's not clear why PATH is split when it contains non-ascii characters (xml_parse function specification?)
So I fixed it as follows and it works.
Is this patch correct?
If you have another solution, please let me know.
```diff
--- a/include/svnlook.php
+++ b/include/svnlook.php
@@ -450,12 +450,12 @@
 			$curMod = $curLog->curEntry->curMod;
 			if ($curMod->action == 'A') {
 				if ($debugxml) print 'Examining added path "'.$curMod->copyfrom.'" - Current path = "'.$curpath.'", leafname = "'.$leafname.'"'."\n";
-				if ($data == $curLog->path) {
+				if ($curLog->curEntry->curMod->path == $curLog->path) {
 					// For directories and renames
 					$curLog->path = $curMod->copyfrom;
-				} else if ($data == $curpath || $data == $curpath.'/') {
+				} else if ($curLog->curEntry->curMod->path == $curpath || $curLog->curEntry->curMod->path == $curpath.'/') {
 					// Logs of files that have moved due to branching
-					$curLog->path = $curMod->copyfrom.'/'.$leafname;
+					$curLog->path = $curMod->copyfrom;
 				} else {
 					$curLog->path = str_replace($curMod->path, $curMod->copyfrom, $curLog->path);
 				}
```

**Comment by ams-tschoening** [comment]
> I checked and found that if the PATH tag in the xml obtained by running "svn log" splits into 2 lines, the link URL is broken. It's not clear why PATH is split when it contains non-ascii characters (xml_parse function specification?)

Do you have an example of such XML, maybe by enabling `$debugxml`? I'm having trouble understanding what your patch changes on newlines in URLs.

    $curLog->curEntry->curMod->path

Isn't that the same like using `$curMod`directly? It's made available some lines earlier:

    $curMod = $curLog->curEntry->curMod;

So, shouldn't the following work as well?

    if ($curMod->path == $curLog->path) {

**Comment by michael-o** [comment]
I would like to see the broken XML too. That really makes me wonder

**Comment by michael-o** [comment]
.

**Comment by n0nel** [comment]
Attach the result executed as `$debugxml = true;` (see [debugxml.log](https://github.com/websvnphp/websvn/files/4935959/debugxml.log) ).
At line 237 you can see that the path is split into 2 lines.
However, the xml is on 1 line (see attached test_log3.xml).

**Reproduction Environment:**
(1)Save the three attached test_log*.xml.txt files to your WevSVN top directory, and rename to .xml.
[test_log1.xml.txt](https://github.com/websvnphp/websvn/files/4935963/test_log1.xml.txt)
[test_log2.xml.txt](https://github.com/websvnphp/websvn/files/4935964/test_log2.xml.txt)
[test_log3.xml.txt](https://github.com/websvnphp/websvn/files/4935965/test_log3.xml.txt)

(2)Make the following changes to include/svnlook.php.
```diff
--- a/include/svnlook.php
+++ b/includesvnlook.php
@@ -566,6 +566,18 @@
 	error_log($string);
 }
 
+function test_get_xml($fname) {
+	$output = array();
+	$file = fopen($fname, 'r');
+	if($file){
+		while ($line = fgets($file)) {
+			$output[] = $line;
+		}
+	}
+	fclose($file);
+	return $output;
+}
+
 // The SVNRepository class
 
 class SVNRepository {
@@ -921,7 +933,23 @@
 
 	function _xmlParseCmdOutput($cmd, $startElem, $endElem, $charData) {
 		$error		= '';
-		$lines		= runCommand($cmd, false, $error);
+		// simulate #106
+		// Save the test_log*.xml files to WebSVN TOP beforehand.
+		if ($charData == 'logCharacterData') {
+			if (strpos($cmd, '--quiet') !== false) {
+				$xml_file = 'test_log2.xml';
+			}
+			elseif (strpos($cmd, '--verbose') !== false) {
+				$xml_file = 'test_log3.xml';
+			}
+			else {
+				$xml_file = 'test_log1.xml';
+			}
+			$lines = test_get_xml($xml_file);
+		}
+		else {
+			$lines		= runCommand($cmd, false, $error);
+		}
 		$linesCnt	= count($lines);
 		$xml_parser	= xml_parser_create('UTF-8');
 
```
(3)Show the following links as the name of the actual repository
http://[websvn_path]/log.php?repname=[any_real_repository_name]&path=%2Ftrunk%2Fdoc%2Ff12%2F%E3%82%B5%E3%83%96%2F&isdir=1&showchanges=1



You can see the length of the Diff link in revision 59 is very long.

**Comment by michael-o** [comment]
So this bacially looks right to me for now. Let's have a look at this path: `/trunk/f02/サブ/d17 001.xls`. To properly encode this for query params one has to use the PHP equivalent of `encodeURIComponent()`. The sample input in my browser's console:
```
encodeURIComponent("/trunk/f02/サブ/d17 001.xls")
"%2Ftrunk%2Ff02%2F%E3%82%B5%E3%83%96%2Fd17%20001.xls"
```

There is unfortunately nothing we can do. @ams-tschoening WDYT?

**Comment by ams-tschoening** [comment]
I still don't get it: Your are wondering about the following logged lines, correct?

    Creating new path
    Action D
    Kind file
    Path name: /trunk/f02/
    Path name: サブ/d01 002.xls
    Ending path

While that might look strange at first, I guess as well that is simply because of the XML-parser forwarding chunks of data as it sees fit to callbacks. But that seems to be honored properly:

	case 'PATH':
		if ($debugxml) print 'Path name: '.$data."\n";
		$data = trim($data);
		if ($data === false || $data === '') return;

		$curLog->curEntry->curMod->path .= $data;

So as long as paths are properly concatenated, there shouldn't be any problem. Where is that "very long" path you are talking about? The following doesn't look that long to me:

> &path=%2Ftrunk%2Fdoc%2Ff12%2F%E3%82%B5%E3%83%96%2F&

Is that were you had thousands of characters? How long were the paths you have used that resulted in such a long URL-segment of many thousands characters? Depending on the path length, encoding to UTF-8 can easily make things a bit longer.

And what is the problem when those URLs contain thousands of characters for a path? Are you not able to open those paths in your browser or what?

**Comment by n0nel** [comment]
The problem occurs when `action="A"`.
A series of operations starting from line 469 of debugxml.log (corresponding to the <path> tag at line 353 of test_log3.xml) starts to make the path longer.
`leafname = "サブ"` has been added to the path because the path is split into "/trunk/f02/" and "サブ/b01 001.xls".

**Comment by n0nel** [comment]
It has been improved by moving the processing of \<path\> tag from the logCharacterData function to the logEndElement function.
```diff
--- a/include/svnlook.php
+++ b/include/svnlook.php
@@ -381,6 +381,35 @@
 
 		case 'PATH':
 			if ($debugxml) print 'Ending path'."\n";
+
+			// The XML returned when a file is renamed/branched in inconsistent.
+			// In the case of a branch, the path doesn't include the leafname.
+			// In the case of a rename, it does.	Ludicrous.
+
+			if (!empty($curLog->path)) {
+				$pos = strrpos($curLog->path, '/');
+				$curpath = substr($curLog->path, 0, $pos);
+				$leafname = substr($curLog->path, $pos + 1);
+			} else {
+				$curpath = '';
+				$leafname = '';
+			}
+
+			$curMod = $curLog->curEntry->curMod;
+			if ($curMod->action == 'A') {
+				if ($debugxml) print 'Examining added path "'.$curMod->copyfrom.'" - Current path = "'.$curpath.'", leafname = "'.$leafname.'"'."\n";
+				if ($curLog->curEntry->curMod->path == $curLog->path) {
+					// For directories and renames
+					$curLog->path = $curMod->copyfrom;
+				} else if ($curLog->curEntry->curMod->path == $curpath || $curLog->curEntry->curMod->path == $curpath.'/') {
+					// Logs of files that have moved due to branching
+					$curLog->path = $curMod->copyfrom.'/'.$leafname;
+				} else {
+					$curLog->path = str_replace($curMod->path, $curMod->copyfrom, $curLog->path);
+				}
+				if ($debugxml) print 'New path for comparison: "'.$curLog->path.'"'."\n";
+			}
+
 			$curLog->curEntry->mods[] = $curLog->curEntry->curMod;
 			break;
 
@@ -433,34 +462,6 @@
 			if ($data === false || $data === '') return;
 
 			$curLog->curEntry->curMod->path .= $data;
-
-			// The XML returned when a file is renamed/branched in inconsistent.
-			// In the case of a branch, the path doesn't include the leafname.
-			// In the case of a rename, it does.	Ludicrous.
-
-			if (!empty($curLog->path)) {
-				$pos = strrpos($curLog->path, '/');
-				$curpath = substr($curLog->path, 0, $pos);
-				$leafname = substr($curLog->path, $pos + 1);
-			} else {
-				$curpath = '';
-				$leafname = '';
-			}
-
-			$curMod = $curLog->curEntry->curMod;
-			if ($curMod->action == 'A') {
-				if ($debugxml) print 'Examining added path "'.$curMod->copyfrom.'" - Current path = "'.$curpath.'", leafname = "'.$leafname.'"'."\n";
-				if ($data == $curLog->path) {
-					// For directories and renames
-					$curLog->path = $curMod->copyfrom;
-				} else if ($data == $curpath || $data == $curpath.'/') {
-					// Logs of files that have moved due to branching
-					$curLog->path = $curMod->copyfrom.'/'.$leafname;
-				} else {
-					$curLog->path = str_replace($curMod->path, $curMod->copyfrom, $curLog->path);
-				}
-				if ($debugxml) print 'New path for comparison: "'.$curLog->path.'"'."\n";
-			}
 			break;
 	}
 }
```
