### ISSUE TITLE
Collapsible Files in Compare View

### ISSUE THREAD

**Issue by k10blogger** [websvnphp/websvn#108]
The expectation is to have a collapsible file comparison view. Here in the snapshot below is an attempted slight improvement in the existing compare view.
![image](https://user-images.githubusercontent.com/4973182/88463735-9666e080-ced2-11ea-812f-28b9c5caa7d0.png)
1 - Is the view of collapsed file. You click on the file bar and it collapse
2 - The expanded view click on view and it expands.
I just used the existing jquery functions to achieve this and here is the commit snapshot
![image](https://user-images.githubusercontent.com/4973182/88463911-f27e3480-ced3-11ea-83e1-7355b4c85113.png)

It is really helpful in scenarios when comparing two folders in subversion with lot of files in them at different revisions. 
I didnt see any use of jquery as it is purely in php so not sure this is an expected way of implementing this.
Any thoughts on this?

**Comment by ams-tschoening** [comment]
Using jQuery would be fine for me, I don't like the inline implementation, though. There's already a JS-directory containing a similar file:

https://github.com/websvnphp/websvn/blob/master/javascript/group-collapse.js

I suggest renaming that file to `collaps[ing|ible].js` and adding your code there. Change all references to that file to the new name, should be one per template only:

    [websvn-test:treeview]
      <script type="text/javascript" src="[websvn:locwebsvnhttp]/javascript/group-collapse.js"></script>
      [websvn-test:opentree]
      [websvn-else]
      <script type="text/javascript">
      //<![CDATA[
      collapseAllGroups();
      //]]>
      </script>
      [websvn-endtest]
    [websvn-endtest]

Would be additionally great if you could get rid of the PHP-check regarding `opentree` and the call to `collapseAllGroups` using plain JS in the renamed file as well. Would make maintenance a bit easier to have those things JS-only and less in template PHP-files. [Other files](https://github.com/websvnphp/websvn/blob/master/javascript/ie-png-transparency.js) check in JS if to apply code or not already as well:

	if (supported)
	   window.attachEvent("onload", correctPNG);

In theory one still needs to provide some icons or stuff to distinguish collapsed vs. uncollapsed table bodies. But if that's too much work for you, I would merge the former changes only as well.

**Comment by k10blogger** [comment]
Okay i will do that. Let me try and put together a commit for you to review. Will try to do this asap.
