### ISSUE TITLE
Synology DS918+ NAS installation ok, cannot acces webpage

### ISSUE THREAD

**Issue by MarkoSan** [websvnphp/websvn#110]
Dear Sirs and Madams!

I am trying to setup WebSVN for my Subversion repositories on my DS918+ NAS. I've installed WebSVN as VirtualHost, set the path to repository in .php file and when I try to access it, I get:
_Unable to find "svnauthz" tool at location "/bin/svnauthz"
![Screenshot from 2020-08-03 12-49-02](https://user-images.githubusercontent.com/3113212/89175285-be67db00-d587-11ea-8591-095709e1f8cc.png)
_
Can someone please help me?

**Comment by ams-tschoening** [comment]
It's like the error message says, you need the binary `svnauthz`. This is available for some binary distributions, you need to find some for your NAS or need to build that tool on your own. The path to that tool can be configured in `config.php`, look for `$config->setSVNCommandPath`.
