### ISSUE TITLE
Support browser suggested language by default.

### ISSUE THREAD

**Issue by ams-tschoening** [websvnphp/websvn#125]
WebSVN supports multiple different languages and allows the user to choose one. But it doesn't seem to automatically detect a language based on the browser preferences. This should be added if necessary.

Additionally, it should be discussed if to still store a chosen language in the cookie. That is the case currently, but when taking browser preferences into account and those change, the cookie values wouldn't be updated once set etc. So it might be considered to really only take browser preferences into account, even though some people consider this bad style. Some people use a browser language for most sites and a site-specific one for some others, like English in case no better language is available.

Looks like PHP provides some helpers already, one needs to have a look at those as well:

https://www.php.net/manual/en/locale.acceptfromhttp.php
https://www.php.net/manual/en/locale.lookup.php

**Comment by k10blogger** [comment]
i investigated this. The websvn does automatically detect a language based on the browser preferences.
It is done in function `getUserLanguage()'.
It also has a way for the hosting server to force a default language as well in the `$config->setDefaultLanguage('en');`
The `getUserLanguage()` takes three arguments one from user, one from server and one from the browser to best estimate the language to serve the user. The cookies is used to store the user defined language that is apart from server defined or browser preferences. 
```
function getUserLanguage($languages, $default, $userchoice) {
	global $config;
	if (!$config->useAcceptedLanguages()) return $default;


	$acceptlangs = isset($_SERVER['HTTP_ACCEPT_LANGUAGE']) ? $_SERVER['HTTP_ACCEPT_LANGUAGE'] : false;
	if (!$acceptlangs)
		return $default;
```
I think cookies should be kept as is as there is not a better to way to handle this.

**Comment by ams-tschoening** [comment]
So as it seems, WebSVN implements language checking based on the corresponding header on its own, which at some point might be changed to PHP's built-in if possible. I guess those simply were not available in the past.

https://github.com/websvnphp/websvn/blob/9e265370fdde3dc2809b125c271bc59f3c9e6318/include/utils.php#L355

Regarding the cookie: The problem with that seems to be that one can't easily reset that to e.g. browser defaults, but only by selecting a concrete language instead or deleting it using dev tools of the browser or alike. Though it's not a big deal at all and I'm not even sure if changing this improves things, so I agree to keep things as they are right now. We chan always change our minds and reopen. :-)
