### ISSUE TITLE
Browse returns 404

### ISSUE THREAD

**Issue by MosfetN** [websvnphp/websvn#133]
Hello,

I upgraded to the last version and I tried to implement MultiViews browsing
https://webserver/websvn/browse.php is working fine but when clicking on a repo, it goes there :
https://webserver/websvn/browse/RepoName? with 404 error :
File does not exist: /var/www/html/websvn/browse/RepoName, referer: https://webserver/websvn/

Is that an issue with my server configuration?
Apache 2.4.29
PHP 7.2
Apache Subversion 1.9.7
WebSVN 2.6.0

**Comment by michael-o** [comment]
Highly likely. MultiViews works for me.

**Comment by michael-o** [comment]
No reaction for two months.
