### ISSUE TITLE
Is there a way to show the repository path or checkout URL for the selected folder?

### ISSUE THREAD

**Issue by oobi** [websvnphp/websvn#138]
We're migrating from VisualSVN (retiring the windows server). WebSVN does more or less everything we need, but I couldn't find a way to display the URL to the actual repository for checkout. My users tend to check the web view to find the path and then paste that into their SVN clients. 

I didn't see an option for it, but hopefully I missed something in config? 

VisualSVN does something like this:
![image](https://user-images.githubusercontent.com/503084/114466835-54cac100-9c2c-11eb-8176-0eca86be3d14.png)

cheers
Chris

**Comment by k10blogger** [comment]
Hi you can do the same by adding the URL to be checked out in the `addRepository` line in the `config.php`

```
$config->addRepository('Repo Name', '/path/to/repo', 'Group Name', 'username', 'password','CheckoutURL');
```
In case you dont want to provide group name, username or password you can leave them blank.
```
$config->addRepository('Repo Name', '/path/to/repo', '', '', '','CheckoutURL');
```

This is how it would look
![image](https://user-images.githubusercontent.com/4973182/114504595-b9961380-9c4c-11eb-9f06-87c5327e1a63.png)

**Comment by oobi** [comment]
@k10blogger  thanks! That worked a treat. I'm using a folder full of repositories so if anyone else stumbles on this, the line is

`$config->parentPath('/home/svn.fi.net.au/svn',` null, false, true, 'https://svn.server.url/');

**Comment by michael-o** [comment]
Question answered? If yes, please close.
