### ISSUE TITLE
PHP 5.4

### ISSUE THREAD

**Issue by rwolosker** [websvnphp/websvn#139]
no version works on version 7 of PHP. I installed PHP version 5.4 with libxml 2.7.8 and it worked.

**Comment by michael-o** [comment]
Nonsense, I am running on PHP Version 7.4.16 for quite some time. Please describe your exact problem.

**Comment by michael-o** [comment]
Please show some real output. PHP 7.0 is long out of support.

**Comment by k10blogger** [comment]
We have not received any input from you in 7 days so closing the issue. Reopen or open a new issue with more details...
