### ISSUE TITLE
Merge all patches from Debian package

### ISSUE THREAD

**Issue by michael-o** [websvnphp/websvn#14]
While working on #8, I have noticed that Debian applied a series of patch too against 2.3.3. It would be good to apply them too.

Package site: https://packages.debian.org/de/jessie/websvn as well as the [tarball](http://http.debian.net/debian/pool/main/w/websvn/websvn_2.3.3-1.2+deb8u2.debian.tar.xz) with the patches.

Notable patches:
31_CVE-2016-1236.patch

This is an umbrella ticket.

Note: some patches won't be applied because they have been fixed in the meantime.

**Comment by tschoening** [comment]
Good catch, should be done after your work in #8 I guess. If one knows how to set a formal dependency on that issue, just do it and tell me. Thanks. :-)

**Comment by michael-o** [comment]
@tschoening agreed. They is aren't issue deps in GitHub like in JIRA. You can only set references.

**Comment by michael-o** [comment]
There was only one mergeable patch.n
