### ISSUE TITLE
Diffs are not shown correctly

### ISSUE THREAD

**Issue by philippecade** [websvnphp/websvn#147]
We see that the diffs are not always shown correctly, in this example the line `// a change` was added but the line above it is highlighted.

![image](https://user-images.githubusercontent.com/804768/125644537-1d253ed0-6a26-4bce-9ccb-9b7e3dabbc04.png)

This is the URL of the screenshot:
`https://xxx/diff.php?repname=sandbox&path=%2Famos_sandbox%2Ftrunk%2Fsrc%2Famos%2Fsandbox%2FHelloWorld.java&rev=266&peg=274`

To compare, here is the output of svn diff for this particular commit:

```
svn diff -r235:266 https://xxx/sandbox/amos_sandbox/trunk/src/amos/sandbox/HelloWorld.java
Index: HelloWorld.java
===================================================================
--- HelloWorld.java     (revision 235)
+++ HelloWorld.java     (revision 266)
@@ -4,5 +4,6 @@
        public static void main(String[] args) {
                // let's see if this gets indexed. A change. And another one.vfvd
                System.out.println("Hello World");
+               // a change
        }
 }
```

WebSVN 2.6.1
Subversion 1.14.1

**Comment by ams-tschoening** [comment]
This has been reported [before](https://github.com/websvnphp/websvn/issues/130#issuecomment-726642714). Please check if `Text_Diff` is installed and if not, install that using PEAR or Composer.

https://websvnphp.github.io/docs/install.html#installation

**Comment by philippecade** [comment]
Sorry for the duplicate and not reading the documentation :/

We confirm that adding this package solves the issue.

**Comment by ams-tschoening** [comment]
> Sorry for the duplicate and not reading the documentation :/

Not a problem, I would expect that if DIFFs somewhat work without `Text_Diff`, they should work correctly as well. It's simply that nobody yet looked into the differences of using `Text_Diff` vs. OS-level. Would be good of course if both simply work, so feel free to have a closer look and make it work.
