### ISSUE TITLE
Use repository name instead of (root) in the breadcrumbs

### ISSUE THREAD

**Issue by didiez** [websvnphp/websvn#150]
Does it make sense to use the repository name instead of the string `(root)` in the breadcrumbs shown in the element `#pathlinks`?

Should it be configurable? In that case, we could preserve the current behaviour (text) for backwards compatibility.

**Comment by michael-o** [comment]
I guess should be configurable...

**Comment by ams-tschoening** [comment]
Guten Tag Michael Osipov,
am Montag, 30. August 2021 um 15:56 schrieben Sie:

> I guess should be configurable...

Before introducing new configs with docs etc.: Is there really any
good usage of "root" vs. the repo name? Remember that we even
introduced "svnauthz" without caring about backwards compatibility and
configs too much. And that realyl slowed down some use-cases... :-)

Looking at the config class, I seems to me that some name to be used
instead of "root" is always vailable. Though, that should be checked
first: Regardless how and how many repos are configured, is there a
repo name to display always or not.

Afterwards let's see if "root" is of any benefit at all before
introducing additional configs, which might make things more complex
for no real benefit. Just look at GitHub, it simply provides the repo
name as part of it breadcrumb as well. I don't see a way to change
this besides renaming the repo.

Mit freundlichen Grüßen

Thorsten Schöning

-- 
AM-SoFT IT-Service - Bitstore Hameln GmbH
Mitglied der Bitstore Gruppe - Ihr Full-Service-Dienstleister für IT und TK

E-Mail: ***@***.***
Web:    http://www.AM-SoFT.de/

Tel:   05151-  9468- 0
Tel:   05151-  9468-55
Fax:   05151-  9468-88
Mobil:  0178-8 9468-04

AM-SoFT IT-Service - Bitstore Hameln GmbH, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 221853 - Geschäftsführer: Janine Galonska

**Comment by ams-tschoening** [comment]
@didiez How do you actually want things to look like? I've had a look at one of my repos and for those repeating the repo name doesn't seem to make too much sense. Wherever I see `(root)`, the repo name isn't that far away. OTOH, there's one skin no showing `(root)` at all, but some HOME-icon instead.

![Clipboard01](https://user-images.githubusercontent.com/6223655/131455666-c300e087-df6c-4643-9c84-1298fbd63947.jpg)
![Clipboard02](https://user-images.githubusercontent.com/6223655/131455668-d16a6a2c-fa94-4c2a-9826-095f242bca0c.jpg)
![Clipboard03](https://user-images.githubusercontent.com/6223655/131455671-38eb919f-39c0-4449-a009-a0fa59d1a44c.jpg)

So what would be the improvement of changing one text to another? Especially as repo name might become large and consume more space in the breadcrumb, while `(root)` is somewhat small. If to change at all, using the HOME-icon in all cases might make more sense to me. This would normalize all skins and remove the visible `(root)`, maybe even saving some space. Either `(root)` or the repo name could then be the title text or the hidden text of the string.

**Comment by k10blogger** [comment]
If we have to change the root. **Then home icon makes more sense than the project name.**
I think using the project name would be confusing.
Take a look at scenario. Let say project name is project-1
```
branches
tags
 - deliverables
   - project-1
     - release-x
trunk
```
I think root is kinda like a keyword to jump to the root directory of the project. If we replace it with project name it kinda creates confusion which project name folder we are looking for. 
I would like to try and avoid that confusion. Root by definition would mean to go to root folder of repository. Hence the keyword.
Though if root needs to be replaced the home icon would be better than project name.

**Comment by didiez** [comment]
Totally agree. Our use case is a bit special as we have a single repo, and the reason behind using the repo name was to ease copy&paste the breadcrumb as a path to the file in svn.
![image](https://user-images.githubusercontent.com/632860/131509472-384532fa-d894-4cba-ad1e-145190e355a0.png)


As we have only one repo, we could leave the expected repo "name" using css `:before { content='myrepo'}` in a custom template. The main problem with this solution is that these css pseudo-classes are not selectable for copy-pasting.
It's not a big deal, and the proposed solution or keeping the current "(root)" text works better in multi-repo installations.

**Comment by ams-tschoening** [comment]
So your use-case would definitely require some kind of config. OTOH, having phrases like `(root)` hard-coded in PHP is bad anyway, would be better to have that in templates or variables or alike. I thought of different things:

# Config for the text to use as root of the breadcrumb

Will work, most likely somewhat easy, not a big fan.

# Button to copy path into clipboard

How about simply adding some button in the menu or next to the breadcrumb, which simply copies the current path into the clipboard using some JS?

That's exactly what @didiez wants in the end and is decoupled from how a breadcrumb looks like etc. It might simply not be available at all in some templates, while such a button might make sense in general and could be placed anywhere and be styled anyhow in the end. It might be some additional `a`, the text is hidden by default, it gets some icon and some JS-clipboard handling.

Though, is most likely a bit more work than introducing some config to change `(root)`-text.

https://stackoverflow.com/a/30810322/2055163

# Improving templates

The template variable which provides the breadcrumb could be splitted up into individual parts: One root-part which either provides `(root)` or the repo name instead and all of the other links like currently. That the real problem right now, that the breadcrumb is built for one variable only and can't be overridden in templates individually. Splitting things up would allow templates to choose which variable to use or even none of those at all. Though, this requires changing templates, @didiez would need to decide if this would be fine for his deployment.

Some example how a breadcrumb is rendered right now:

```html
<div id="pathlinks">[websvn:pathlinks]</div>
```

This would be something like the following with a splitted variable:

```html
<div id="pathlinks">[websvn:path_links_root_root]/[websvn:path_links]</div>
```

vs.

```html
<div id="pathlinks">[websvn:path_links_root_repo]/[websvn:path_links]</div>
```

vs.

```html
<div id="pathlinks"><a href="..." class="root">One ROOT to rule them all!</a>/[websvn:path_links]</div>
```

The last example is without any pre-defined root for some reason. In PHP things [look like the following](https://github.com/websvnphp/websvn/blob/92151a9ac141882fedc0cb3e207827c8f6690137/include/utils.php#L49) right now:

```php
$vars['pathlinks'] = '<a href="'.$pathSoFarURL.'" class="root"><span>(root)</span></a>/';
```

Which would be changed to something like the following:

```php
$vars['path_links']                  = '';
$vars['path_links_root_root'] = '<a href="'.$pathSoFarURL.'" class="root"><span>(root)</span></a>';
$vars['path_links_root_repo'] = '<a href="'.$pathSoFarURL.'" class="root"><span>$REPO_NAME</span></a>';
```

# Opinions?

Let's not make things more difficult as necessary, though there's some chance to extract some basic concept of what @didiez needs. Especially if he implements on its own. ;-)

**Comment by k10blogger** [comment]
I dont think we need to do anything here. 

In case of 
"Button to Copy path into clipboard" 

I am pretty sure most browser support this already. Have a look at the snapshot below. We already do this.
![image](https://user-images.githubusercontent.com/4973182/132103601-7ef7e44f-0235-4e9f-a141-056b6a696c43.png)

In edge browser just selecting and hitting ctrl + c gives a desired result. (Copying the path to the clipboard) 

In case of 
"Improving templates"
In case of splitting the path in templates most users, in our organization already copies the selected path from after the (root) itself. 

So i dont think we need to do any changes here.

**Comment by ams-tschoening** [comment]
> I am pretty sure most browser support this already. Have a look at the snapshot below. We already do this.

Your example ignores the parts of the path @didiez cares about, namely the root itself, which is not the name `(root)`. :-) His users currently need some more steps to accomplish this, so no wonder he's asking for improvement.

**Comment by didiez** [comment]
Hi all, I have been afk a few days. 
The main blocker for our requirement is that there is no way to change the text inside de first links rendered in the `#pathlinks` element by only tweaking the templates, as is hardcoded in `utils.php`.
Even the simplest form of parametrization or composition would work for us.

Something like this would allow a flexible way to customize the text, keeping the current behaviour, with a minimal change in the codebase:
```php
// configclass.php
class WebSvnConfig {
    ...
    var $rootNameProvider;

    function getRootDisplayName($rep) {
        return $this->rootNameProvider ? ($this->rootNameProvider)($rep) : '(root)' ;
    }
    ...
}
```
```php
// utils.php (line 49)
$vars['pathlinks'] = '<a href="'.$pathSoFarURL.'" class="root"><span>'.$config->getRootDisplayName($rep).'</span></a>/';
```



With this two changes, customizing the text would be as simple as registering a function in `config.php`, in our case would be:
```php
$config->rootNameProvider = fn($rep) => $rep->getDisplayName();
// more examples
// $config->rootNameProvider = fn() => 'ROOT';
```
If not configured, the actual text `(root)` would be used for every repo.

I could do a PR with this idea if it seems ok to you.

**Comment by didiez** [comment]
Another idea just came to my mind after sending my previous comment. It could be really useful to also include de current user `$lang` to allow i18n texts. 
For example (currently there is no `ROOT` key in languages; just to show how could it be used):
```php
// config.php
$config->rootNameProvider = fn($rep, $lang) => $lang["ROOT"]; 
```

**Comment by k10blogger** [comment]
This would work and PR would be nice :) ...

**Comment by ams-tschoening** [comment]
Code like that shouldn't be part of a config class at all, mostly containing function calls right now is bad enough already. Making things additionally difficult with lambdas and stuff is a mistake in my opinion. Those phrases should be part of the templates or `$lang` or alike, but not the result of arbitrary callbacks in config classes.

**Comment by didiez** [comment]
> Code like that shouldn't be part of a config class at all, mostly containing function calls right now is bad enough already. Making things additionally difficult with lambdas and stuff is a mistake in my opinion. Those phrases should be part of the templates or `$lang` or alike, but not the result of arbitrary callbacks in config classes.

I see your point. The idea behind providing a function as config is to give full control to the developer/administrator, though.
Maybe, the `$lang` idea adds complexity without an actual reason (we don't need that at the moment)
For our use case, a simple boolean config `useRepositoryNameAsRoot` would work. Simpler but less flexible in case another similar requirement arises.

**Comment by ams-tschoening** [comment]
Did you recognize my [suggestion about changed templates](https://github.com/websvnphp/websvn/issues/150#issuecomment-909458531), `Improving templates`? That could easily be combined with using `$lang` for some phrase other than `(root)`, provides your repo name if you want to by slightly changing templates and one could easily create a boolean config only switching between using `*_root_root` and `*_root_repo`.

```html
<div id="pathlinks">[websvn:path_links_root_config]/[websvn:path_links]</div>
```

```php
$vars['path_links']                  = '';
$vars['path_links_root_root'] = '<a href="'.$pathSoFarURL.'" class="root"><span>$lang["BREADCRUMB_REPO_ROOT"]</span></a>';
$vars['path_links_root_repo'] = '<a href="'.$pathSoFarURL.'" class="root"><span>$REPO_NAME</span></a>';
$vars['path_links_root_config'] = $config->$breadcrumbRepoRootAsRepo ? $vars['path_links_root_repo'] : $vars['path_links_root_root'];

$lang['BREADCRUMB_REPO_ROOT'] = '(root)';
```

**Comment by didiez** [comment]
I'm ok with that solution too :+1: . Just seemed to me a bit simpler and more flexible the "pluggable" function solution. 
Nevertheless, if this goes against the rules/style of the `config.php` philosophy, no problem at all, either way is fully functional for us.
As a developer/administrator of an installation, I would expect to modify as little as possible (ideally a configuration property in `config.php`).

**Comment by ams-tschoening** [comment]
> Nevertheless, if this goes against the rules/style of the `config.php` philosophy[...]

I was only telling my opinion, your are all free to vote against it of course. I won't block if most of us consider your approach the better one.

> As a developer/administrator of an installation, I would expect to modify as little as possible (ideally a configuration property in config.php).

Same here, that's why I would introduce the additional boolean flag to switch between repo name and ROOT-phrase used in the templates. Though, in my opinion again, such a boolean flag is better than to put arbitrary code into the config. Additionally, people are free to change their templates however they like this way as well, e.g. not rendering some root component at all or something completely different, hard-coded instead. that wouldn't be possible that easy with your approach, because the individual component rendered in the templates are still the same, only some textual content would change depending on the config. But you would not be able to break it into different parts.

Of course, might be not necessary for anyone at all... ;-)

**Comment by ams-tschoening** [comment]
@didiez I've created a PR for what I've suggested to not burden my ideas entirely on other people. Please have a look and test, a short test for my setup worked as expected. But things are quick'n'dirty right now.

**Comment by didiez** [comment]
Thanks @ams-tschoening. I've just tested it and works like a charm using the new flag in `config.php`.
Thanks again for your time :+1:
