### ISSUE TITLE
websvn - possibility to commit files

### ISSUE THREAD

**Issue by francwalter** [websvnphp/websvn#154]
Hallo
I am sure this question is old and somewhere explained but I dont find it.
Is there a way, to do more than listing, do commit and such stuff?
Sorry if that is a silly question. Many years ago, I used Polarion (with Tomcat) for that, but it doesnt exist anymore.
Thanks.
frank

**Comment by ams-tschoening** [comment]
Guten Tag franc,
am Donnerstag, 21. Oktober 2021 um 18:56 schrieben Sie:

> I use svn only as versioned backup for myself, I have to admit. Nothing more.
> GIT would be overkill for that, I think.

In your usage-scenario there's not much difference between GIT and SVN
at all. Why do you need something running in the browser?

Simply use some other GUI client for your OS of choice, like
TortoiseSVN etc. Those are most likely even easier to setup than
WebSVN. The latter targets read-only collaboration by multiple users
accessing the same repo.

Mit freundlichen Grüßen

Thorsten Schöning

-- 
AM-SoFT IT-Service - Bitstore Hameln GmbH
Mitglied der Bitstore Gruppe - Ihr Full-Service-Dienstleister für IT und TK

E-Mail: ***@***.***
Web:    http://www.AM-SoFT.de/

Tel:   05151-  9468- 0
Tel:   05151-  9468-55
Fax:   05151-  9468-88
Mobil:  0178-8 9468-04

AM-SoFT IT-Service - Bitstore Hameln GmbH, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 221853 - Geschäftsführer: Janine Galonska
