### ISSUE TITLE
Deprecated: Function strftime() is deprecated

### ISSUE THREAD

**Issue by java4devgmail** [websvnphp/websvn#167]
Hi

I tried to install websvn on FreeBSD 13.1-RELEASE
I tried both vesions
websvn-php80-2.7.0             Online Subversion repository browser
websvn-php81-2.7.0             Online Subversion repository browser

and on websvn-php81-2.7.0  I am seeing following messages on top of the window
Deprecated: Function strftime() is deprecated in /usr/local/www/websvn/include/svnlook.php on line 447

Deprecated: Function strftime() is deprecated in /usr/local/www/websvn/include/svnlook.php on line 296

the issue does not appear on websvn-php80-2.7.0 

Kind Regards
Nikolas

**Comment by michael-o** [comment]
I do plan to tackle the FreeBSD port end of summer. But will likely skip php 8.0 for 8.1.

**Comment by michael-o** [comment]
Thanks for the report
