### ISSUE TITLE
Bug in Diff view

### ISSUE THREAD

**Issue by ogou** [websvnphp/websvn#181]
Hi all,
It seem to have a bug in the diff view.

When I look in the compare view, I can see my change (for example, I've change NOACCESS <->TEST) 
But when I look in the Diff view, the change is not on the correct line (it should be on the line 230 and not on the line 229).

![Capture d’écran 2022-09-29 095950](https://user-images.githubusercontent.com/9967900/192975846-c50d3448-f1da-478b-91fa-c342271ad847.jpg)
![Capture d’écran 2022-09-29 095914](https://user-images.githubusercontent.com/9967900/192975868-0556242a-619f-4d89-b45c-2a34cd8b4dd7.jpg)

**Comment by michael-o** [comment]
Let me try to reproduce this with master...

**Comment by michael-o** [comment]
This is already fixed on master:
![grafik](https://user-images.githubusercontent.com/573017/192979197-066ef74f-cf64-437b-ba22-84ba6c5089e7.png)

**Comment by ogou** [comment]
I've just upgrade to the 2.8 version and I steel have the problem ...
any idea ?

**Comment by michael-o** [comment]
Please share a screenshot

**Comment by ogou** [comment]
![Capture d’écran 2022-10-19 083003](https://user-images.githubusercontent.com/9967900/196613919-b1966f68-a4b9-47d5-80b7-5a7a79825130.jpg)

**Comment by michael-o** [comment]
Thanks for the screen. Are you using Horde_Text_Diff or `diff(1)`?
Can you show please the file at r45 and r46?

**Comment by michael-o** [comment]
> File in version r45 and r46 [diff.zip](https://github.com/websvnphp/websvn/files/9817743/diff.zip)
> 
> I'm using diff(1)

Thanks, checking...

**Comment by michael-o** [comment]
I can confirm this with BSD `diff(1)`:
![grafik](https://user-images.githubusercontent.com/573017/196641952-652da580-adbb-4718-92fd-f4b323670123.png)

**Comment by michael-o** [comment]
I think I have found the bug and you are not going to like it...

**Comment by ogou** [comment]
gloupsss ;-(  ..... can you share your analyse ?

**Comment by michael-o** [comment]
I will provide a PR for testing shortly.

**Comment by michael-o** [comment]
@ogou This killed your diff: https://github.com/websvnphp/websvn/pull/183/files#diff-f1dac0e795ad106be8d21b0f59bec5c24faaffadd2a7964950afd67337eb8b26

**Comment by michael-o** [comment]
@ogou Please verify this PR in the next couple of days and let me know.

**Comment by ogou** [comment]
@michael-o, It's ok for me, ticket close !


![Capture d’écran 2022-10-20 180729](https://user-images.githubusercontent.com/9967900/197001331-3dfcc6d6-8c42-4a9f-9e04-bb76879554af.jpg)
