### ISSUE TITLE
 Install websvn on Debian 10 problem

### ISSUE THREAD

**Issue by 3956ray** [websvnphp/websvn#182]
Hi All,

I got a problem when I install websvn on Debian 10 (VMware).

I used this command.
`sudo apt-get install websvn`
and I got error like
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package websvn
```
Can anyone help me?

OS:Debian 10(VMware)
PHP 7.3.31-1
Apache/2.4.38 (Debian)

By the way, I don't find a good installation guide for websvn on the internet yet. Can anyone recommand me any suggestion or website？

**Comment by michael-o** [comment]
You must consult Debian package maintainer, the latest supported version is https://github.com/websvnphp/websvn/releases/tag/2.8.0. PHP 7.3.x is EOL too.

**Comment by k10blogger** [comment]
For installation instruction from source refer to the guide here
https://websvnphp.github.io/docs/install.html

**Comment by michael-o** [comment]
No response, downstream packages are supported by downstream maintainers.
