### ISSUE TITLE
PNG file extension missing

### ISSUE THREAD

**Issue by danielmarschall** [websvnphp/websvn#186]
Hello,

I noticed that at **include/setup.php** , in the array `$contentType` , the PNG file extension (`image/png`) and SVG (`image/svg+xml`) are missing. I think they should be added because they are very often used.

Best regards
Daniel Marschall

**Comment by michael-o** [comment]
Indeed, please raise a PR.

**Comment by michael-o** [comment]
@danielmarschall Have a look at #187.
