### ISSUE TITLE
WebSVN does not allow downloading directories and files whose names contain the @ sign

### ISSUE THREAD

**Issue by sskokorin** [websvnphp/websvn#189]
I know that the presence of the @ sign in the name of the repository is regarded by the Subversion as the boundary beyond which the version of the revision begins. However, the Subversion documentation says that this behavior can be bypassed.
I'm not familiar with the PHP programming language and would like the ability to download files with names containing the @ sign to be added to the code. Is it possible?

![image](https://github.com/websvnphp/websvn/assets/69642529/eb04f770-7d29-4cae-b38f-ff9133633f2b)

**Comment by michael-o** [comment]
Good catch! Fixed a similar problem with Maven SCM many years ago. Let me check this week.

**Comment by michael-o** [comment]
Looking into this one. Which Subversion are you running?

**Comment by sskokorin** [comment]
Apache Subversion

```
root@svn:~# svn --version --quiet
1.14.1
```

**Comment by michael-o** [comment]
I have reported [this](https://www.mail-archive.com/users@subversion.apache.org/msg29597.html) already many years ago: https://lists.apache.org/thread/lonftwtj2kmnjf5mlp91jyxz9xlsgv3d

**Comment by michael-o** [comment]
I have now applied the same fix as with Maven SCM: https://github.com/apache/maven-scm/commit/66a260a9107b6cec0c4ebfb9a42e9cc808512e90?w=1

**Comment by michael-o** [comment]
@sskokorin If this works for you, I'd cut a release this month.

**Comment by sskokorin** [comment]
I have tried this fix on all of my repositories. It does work. Thanks a lot!

**Comment by sskokorin** [comment]
> @sskokorin If this works for you, I'd cut a release this month.

I have tried this fix on all of my repositories. It does work. Thanks a lot!

**Comment by michael-o** [comment]
> > @sskokorin If this works for you, I'd cut a release this month.
> 
> I have tried this fix on all of my repositories. It does work. Thanks a lot!

Good! Just tagged 2.8.2.
