### ISSUE TITLE
Move documentation to website

### ISSUE THREAD

**Issue by joubertredrat** [websvnphp/websvn#19]
Today on repo have a folder `./doc` with install and other documentation, but is necessary move this to site.

**Comment by joubertredrat** [comment]
@michael-o I think for now put in html and in future consider remake all site in markdown or other static site supported by gh-pages, what you think?

**Comment by michael-o** [comment]
Makes sense, MD move should be made after 2.4.

**Comment by joubertredrat** [comment]
I will provide this then.

**Comment by joubertredrat** [comment]
Done. https://websvnphp.github.io/docs/
