### ISSUE TITLE
Character encoding mistakes arising from change in mb_detect_encoding

### ISSUE THREAD

**Issue by andrew-hardie** [websvnphp/websvn#195]
Some files are rendered in the filedetails.php display according to the wrong character encoding (win1252 when the are actually utf8). This can happen with text that is non-Latin-alphabet (I noticed it with regard to some Sinhala text). 

The issue is in  include/command.php, function detectCharacterEncoding(). PHP's mb_detect_character_encoding() no longer checks the list of possible encodings in order (as of, I believe, PHP8.1) but rather returns whichever on the list it finds to fit best. So, although UTF-8 is first on the list supplied, it can be detected as 1252 if the particular UTF-8 bytes happen to fit whatever profile is used for 1252. 

On my installation, the patch below fixes the issue by using mb_check_encoding() instead (and adds a pcre based fallback in case none of the tested PHP functions are present, though all should be). 
```
27,31c27,30
<       if (function_exists('mb_detect_encoding')) {
<               // @see http://de3.php.net/manual/en/function.mb-detect-encoding.php#81936
<               // why appending an 'a' and specifying an encoding list is necessary
<               return mb_detect_encoding($str.'a', $list);
< 
---
>       if (function_exists('mb_check_encoding')) {
>               foreach ($list as $item) {
>                       if (mb_check_encoding($str, $item)) return $item;
>               }
36a36,38
>       } else {
>               // since windows-1252 is a superset of iso-8859-1, the following works for either.
>               return preg_match('//u', $str) ? 'UTF-8' : 'windows-1252';
```

**Comment by michael-o** [comment]
> Some files are rendered in the filedetails.php display according to the wrong character encoding (win1252 when the are actually utf8). This can happen with text that is non-Latin-alphabet (I noticed it with regard to some Sinhala text).
> 
> The issue is in include/command.php, function detectCharacterEncoding(). PHP's mb_detect_character_encoding() no longer checks the list of possible encodings in order (as of, I believe, PHP8.1) but rather returns whichever on the list it finds to fit best. So, although UTF-8 is first on the list supplied, it can be detected as 1252 if the particular UTF-8 bytes happen to fit whatever profile is used for 1252.
> 
> On my installation, the patch below fixes the issue by using mb_check_encoding() instead (and adds a pcre based fallback in case none of the tested PHP functions are present, though all should be).
> 
> ```
> 27,31c27,30
> <       if (function_exists('mb_detect_encoding')) {
> <               // @see http://de3.php.net/manual/en/function.mb-detect-encoding.php#81936
> <               // why appending an 'a' and specifying an encoding list is necessary
> <               return mb_detect_encoding($str.'a', $list);
> < 
> ---
> >       if (function_exists('mb_check_encoding')) {
> >               foreach ($list as $item) {
> >                       if (mb_check_encoding($str, $item)) return $item;
> >               }
> 36a36,38
> >       } else {
> >               // since windows-1252 is a superset of iso-8859-1, the following works for either.
> >               return preg_match('//u', $str) ? 'UTF-8' : 'windows-1252';
> ```

Can you raise a PR with that?

**Comment by andrew-hardie** [comment]
Sample text which has the problem:
```
මධ්‍යස්ථානවලට යෑමට ඉඩ කඩ ලබා නොදීමට පාතාල මැර කණඩායම් යොදවා සාහසික ප්‍රචණ්ඩ
ක්‍රියා සිදුකර ඔවූන්ට තර්ජනය කිරීමේ සැලසූමක් ක්‍රියාත්මක කිරීමට ඇතැම් ප්‍රදේශවල
``` 

I don't use Github and only signed up to leave this report, so I don't know what a PR is or how to raise one, sorry. But you have the patch.

**Comment by michael-o** [comment]
Here it is: https://github.com/php/php-src/issues/8279

**Comment by michael-o** [comment]
I confirmed your patch to work. Thanks!
