### ISSUE TITLE
WebSVN's diffs do not work on Windows

### ISSUE THREAD

**Issue by raspopov** [websvnphp/websvn#210]
The next code at include\command.php:123:
``` c
	// https://github.com/websvnphp/websvn/issues/75
	// https://github.com/websvnphp/websvn/issues/78
	if ($config->serverIsWindows) {
		if (!strpos($cmd, '>') && !strpos($cmd, '|')) {
			$opts = array('bypass_shell' => true);
		} else {
			$cmd = '"'.$cmd.'"'; <-- THIS LINE
		}
	}
```
produces the wrong escaping of cmd.exe on Windows for example:
`cmd.exe /s /c """C:\svn\svn" --non-interactive --config-dir C:\svn\config --trust-server-cert cat -r 15 "file:///C:/Repositories/c4u/trunk/include/CoTaskMem.h@16" > "C:\php\tmp\1DDA.tmp"""`
i.e. 3 quotation marks at the beginning and end of the command line instead of 2.
This bug effectively turns off the diffs of the revisions.

PHP 8.2.7, WebSVN 2.8.3

**Comment by michael-o** [comment]
Will try to take a look. Using the `cmd.exe`/`sh` is ugly in many ways. @slawekjaranowski, we know this crap from m-s-utils and p-utils...

**Comment by michael-o** [comment]
Here is the C code:
https://github.com/php/php-src/blob/b06fedb41d560f756dfb5d964b0d36a224e44dc7/ext/standard/proc_open.c#L645-L649

Did you try to remove the redudant quotes and see what happens?

**Comment by michael-o** [comment]
I bet that quoting isn't necessary anymore...

**Comment by raspopov** [comment]
> Did you try to remove the redudant quotes and see what happens?

To fix the diffs functionality in my WebSVN installation, I already commented out the above line of code.

The `/s` option removes the single quotes from both sides of the `cmd.exe` command line, `cmd.exe` is added when `bypass_shell = false` if no redirection is required.

**Comment by raspopov** [comment]
I found when it was changed: [ext/standard/proc_open.c](https://github.com/php/php-src/commit/9ca449e0a803cb9d1d40fd6b83f2da1e6a7b46d9?diff=split&w=0#diff-0fb2e3ebee149b26f75a83db7b0f8194009afccdb54b8cf51a7986031af64c87).
At the time, this function was an big monster yet and PHP was version 8.0.0 RC2.

**Comment by michael-o** [comment]
> I found when it was changed: [ext/standard/proc_open.c](https://github.com/php/php-src/commit/9ca449e0a803cb9d1d40fd6b83f2da1e6a7b46d9?diff=split&w=0#diff-0fb2e3ebee149b26f75a83db7b0f8194009afccdb54b8cf51a7986031af64c87). At the time, this function was an big monster yet and PHP was version 8.0.0 RC2. This makes sense, I hit into that issue after upgrading from PHP 5 to PHP 8. 🤔

Found the same, 8 had a big hit. Will address this issue.
