### ISSUE TITLE
Rendering some file types not working

### ISSUE THREAD

**Issue by matthias-ko** [websvnphp/websvn#216]
Hi, 
I have a problem rendering different filetypes (.cpp, .h, .tcl ...) in websvn 2.8.2:
![image](https://github.com/websvnphp/websvn/assets/158464505/15499649-66c6-4868-9a85-d1f037c2a0da)

On the old websvn 2.3.0 there were no problems:
![image](https://github.com/websvnphp/websvn/assets/158464505/330ae7da-fbee-427d-b759-de6272d095a2)

Any help appreciated: Thanks!
Matthias

**Comment by matthias-ko** [comment]
Nothing noticeable in the server log.
If I rename the same file to something which already works (like txt or log) it renders it normally.
If set config.php $contentType['.h'] = 'text/plain';  then I get a new button which enables open it in plain text butr this is not a desirable workaround.

![image](https://github.com/websvnphp/websvn/assets/158464505/baec1993-c65f-4048-8ea5-bef0ca2b2c64)

**Comment by michael-o** [comment]
Can you check all properties on that node via command line? I have the feeling that it is set to `application/octet-stream`.

**Comment by michael-o** [comment]
Can you give `svn pl --verbose {path}`. It is not the mime-type, I tried here. I bet that some command fails for some reasons.

**Comment by matthias-ko** [comment]
I figured it out:
Forgot to write that I was using GeSHi. Disabling GeSHi it renders in plain text without problems.
But as we want GeSHi I found that it is not compatible with PHP8.1. Although it stated it depends on PHP5.3 I just removed PHP8.1 and installed PHP7.4 and now it works:

![image](https://github.com/websvnphp/websvn/assets/158464505/e1d37249-ebde-47a4-a04c-854d94028712)

![image](https://github.com/websvnphp/websvn/assets/158464505/767594a3-5c10-4853-ac33-1711a60ff1ed)

**Comment by michael-o** [comment]
You problem is that you have 1.0.9.0 which you need 1.0.9.1. This one works woth PHP 8.x flawlessly for me. For PEAR Geshi in FreeBSD, I applied a one-off patch which you need here as well: https://github.com/freebsd/freebsd-ports/commit/73e6b03413c952554b336f27f00d268dc88b9fc2

Contact your package maintainer.
