### ISSUE TITLE
Slow displaying of SVN view log in webSVN

### ISSUE THREAD

**Issue by matthias-ko** [websvnphp/websvn#219]
Displaying the history of commits by clicking “View log” is very slow. It takes 10 seconds per “view log click”, sometimes it takes almost 30 seconds.
I am not able to find out the right pattern to reproduce the problem. filetype, number of revisions, ..... not the cause.

Any idea how to solve this. 
Thank you!

**Comment by michael-o** [comment]
Can you check with `svn log <item>` how log it takes?

**Comment by matthias-ko** [comment]
svn log /path/to/the/same/item works flawlessly. It shows instantly.

**Comment by michael-o** [comment]
Similar to: https://github.com/websvnphp/websvn/issues/78

Can you disable access/permissions check temporarily and see whether it makes a difference?

**Comment by matthias-ko** [comment]
Thank you. 
Commenting/disabling $config->useAccessFile('/path/to/my/access/file/svn-auth.conf'); increases loading of log significantly.
Any idea of how to speed up and preserve the svn-auth.conf file?

**Comment by michael-o** [comment]
Exactly what I have expected 😪
How many items are being logged here? Please see #78 on how this could be solved in the future.  I don't see a better/cleaner way.

**Comment by matthias-ko** [comment]
I have quite big repos with lots of items. I've migrated from an websvn 2.3.0 where all worked flawlessly to the 2.8.2 where thing are not as smooth.
I'll talk to the development team about this issue.
Thank you for all help!
