### ISSUE TITLE
Installing on Ubuntu Server 20.04 - does it affect the SVN operations?

### ISSUE THREAD

**Issue by bob-swede** [websvnphp/websvn#220]
First post here, coming here from the subversion mail list on advice from Michael Osipov...

I have an Ubuntu Server (no GUI) which is now at version 20.04 LTS.
It was originally 16.04 LTS and upgraded to 18.04 and then 20.04 but I do not want to repeat the upgrade again...

On that server I installed a Subversion server to act as a backup system for the main Subversion server running on a Windows Server 16 PC.
It uses VisualSvn as the service (did not know better when it was installed back in 2018). The main server sends updates to the backup nightly using svnsync.

Now I want to convert it all to Linux and as a start I want to check the web interface on the Ubuntu backup server.
The backup uses Apache SVN integration and is accessed via https. 

The VisualSvn main server has a web based user interface with which one can navigate among the various projects and view the files, commit messages etc. But this is not available on the backup ApacheSVN server and I would like to have something allowing more access via a web browser rather than less...

So I am looking at the WebSVN project and have some basic questions right now:

1) If I install WebSVN on the Ubuntu 20.04 backup server, does that in any way modify the existing Apache-Svn configuration? And can it even be installed given that the backup server no longer receives any package updates?
Svn itself sits at 1.13.0 (r1867053)...

2) Can WebSVN operate over the network from a  **different** computer towards the backup SVN server?
I.e. can I instead of modifying the backup server use a brand new Linux Ubuntu server with WebSVN to access the repositories on the backup server for display purposes? And have all the most recent package versions on that device....

The plan is to replace the Windows Server and VisualSvn with Apache SVN + WebSvn on a new Linux server but before doing that I want to be able to verify that it will operate using our existing Ubuntu backup server.

Our repositories are at present about 40 GB in size.

**Comment by michael-o** [comment]
I'll try to respond to you in the next couple of days...

**Comment by michael-o** [comment]
Side note: If you previously relied on Kerberos to authenticate you can continue to do so, please read my article on that: http://home.apache.org/~michaelo/svn-enterprise-auth/. Works like on day one.

**Comment by michael-o** [comment]
First Q: No, WebSVN never modifies any data in a Subversion repository. It only reads data.
Second Q: Yes, you can do WebSVN over the network, that is supported, but consider: Latency and WebSVN require authenticated access to all repos to present content. I, personally, do this locally only. I would set up WebSVN on the backup server to have best perf.

> The plan is to replace the Windows Server and VisualSvn with Apache SVN + WebSvn on a new Linux server but before doing that I want to be able to verify that it will operate using our existing Ubuntu backup server.

Not a problem at all, I have been running for the past 15 years on FreeBSD w/o any pain, but I do recommend to upgrade to 1.14.x first. 1.13.x is dead.

**Comment by michael-o** [comment]
Please let me know whether this works for you..

**Comment by michael-o** [comment]
Closing since information has been provided and no feedback given.
