### ISSUE TITLE
Discontinue changes.txt in favor of GitHub milestones

### ISSUE THREAD

**Issue by michael-o** [websvnphp/websvn#29]
Let's use the milestones in the tickets to track version-related changes. This makes users way easier to scan through changes w/o having an incomplete file or worse reading `git log` for every single new version.

**Comment by tschoening** [comment]
Would you like to drop the file entirely or keep it as is and only add some describing sentence to look at the milestones here?

**Comment by joubertredrat** [comment]
I agree with this.
