### ISSUE TITLE
Evaluate use of $_SERVER['CONTEXT_PREFIX'] for $locwebsvnhttp with MultiViews

### ISSUE THREAD

**Issue by michael-o** [websvnphp/websvn#48]
I came across that the context path (`$locwebsvnhttp`) fo the app has to be set manually in `browse.php`. Can't we leverage `$_SERVER['CONTEXT_PREFIX']` as the default config? This works at least for me in the MultiViews case.

One still can change this value on his/her server.

WDYT?

**Comment by tschoening** [comment]
Sounds good for me. I guess such things should be moved to the config class in the long term anyway.

**Comment by michael-o** [comment]
@tschoening Agreed, will create a PR for.
