### ISSUE TITLE
Update code to PHP 7.0

### ISSUE THREAD

**Issue by joubertredrat** [websvnphp/websvn#5]
This code was made for PHP 5.2, but this version was discontinued since few years ago.

I think that is good to update source code to PHP 7 for support to install this project on new OS versions, like Ubuntu 16.04/17.04 LTS, CentOS 7.1 and others.

What you think @tschoening?

**Comment by tschoening** [comment]
I have it running on UB 16.04 with PHP 7, so there might not be any need to additionally change things? I suggest waiting for people complaining about things not working on modern PHP and fixing those problems then. WebSVN doesn't seem to have unit tests and such, so you might make things worse than they are for only little benefit.

**Comment by joubertredrat** [comment]
Hi @tschoening. I will make tests here then.

**Comment by jmwf** [comment]
We have WebSVN running in PHP7.1 and most of the things work.
But the parts where webSVN relies on the pear.php stuff, like using download links or comparing with previous version, unfortunately always returns an error:

> Parse error: syntax error, unexpected 'new' (T_NEW) in /www-server/websvn/lib/pear/Text/Diff.php on line 383

or something similar.
/J

**Comment by tschoening** [comment]
The problems with PEAR can easily be solved:

https://github.com/websvnphp/websvn/pull/3

**Comment by jmwf** [comment]
Thanks!
That resolves my biggest issue!
Any plans for a tagged and released version of this?

**Comment by didigomaciel** [comment]
@tschoening, still some problems should occur with php 7.0. It's necessary to remove & from &new in the `<websvn-path>/lib/pear/Text/Diff/Diff.php` and  `<websvn-path>/lib/pear/Text/Diff/Engine/native.php files`.

Changing these two was enough for websvn work in PHP7.

**Comment by tschoening** [comment]
@didigomaciel According to PR #3, you simply would have needed to delete all local pear files and install new official packages as replacement. That way you don't need to deal with individual problems. That PR should has been merged already as well.

**Comment by lkppo** [comment]
Hello,

I had ported webvsn 2.3.3 to support PHP from version 5.3 to 7.2.  Are you interested in this work?

PS: I find it really unfortunate to break the portability of the software and make it more difficult to install just for 3 libraries. Especially since in this case we no longer master the installed version of these libraries. The bare minimum is to document these dependencies.

Regards,

**Comment by tschoening** [comment]
> I had ported webvsn 2.3.3 to support PHP from version 5.3 to 7.2.  Are you interested in this work?

If it's not related to the formerly bundled PEAR libs, feel free to add PRs. The last bundled lib will be removed with #8, so changes to those are simply not worth your time and it's unlikely that those libs will be bundled again.

> The bare minimum is to document these dependencies.

You are right and I added basic docs about those dependencies in PR #9.

**Comment by michael-o** [comment]
Hasn't this issue been resolved with recent PR?

**Comment by joubertredrat** [comment]
Yes @michael-o we can consider this closed.

**Comment by tschoening** [comment]
Closed by #31.
