### ISSUE TITLE
Problem in Diff.php

### ISSUE THREAD

**Issue by RenHoekNL** [websvnphp/websvn#53]
websvn-2.3.3.tar.gz, Ubuntu 16.04.4 LTS, PHP 7.0.30-0ubuntu0.16.04.1

I'm getting:

PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /var/www/html/websvn/lib/pear/Text/Diff.php on line 383

**Comment by RenHoekNL** [comment]
Removing the ampersand in front of 'new' in files:
websvn/lib/pear/Text/Diff.php
websvn/lib/pear/Text/Diff/Engine/native.php

seems to fix the problem. 

The original package at https://github.com/pear/Text_Diff also seems to have fixed this issue already.

**Comment by michael-o** [comment]
The `lib` directory is gone, so no bug in WebSVN anymore. You are advised to ask your OS vendor for updates or update Text_Diff yourself.
