### ISSUE TITLE
Updated documentation / site?

### ISSUE THREAD

**Issue by philip** [websvnphp/websvn#58]
I'm struggling to differentiate between the old and new documentation. 

This is a request to document:
* How to install websvn (from git; today this means 2.4)
* How to upgrade an old 2.3.3 installation to use this fork/version (likely, 2.3 -> 2.4)
* The current status of the websvn project; specifically related to this fork and the 2.3.3 version

For example, `changes.txt` might reference 2.4 somehow; maybe with a link on top to the 2.4 milestone page?

**Comment by ams-tschoening** [comment]
> How to install websvn (from git; today this means 2.4)

The instructions didn't change much and if you are in the process of installing anyway, it seems like a good idea to provide PRs with what you are missing.

https://websvnphp.github.io/docs/install.html#installation

> How to upgrade an old 2.3.3 installation to use this fork/version (likely, 2.3 -> 2.4)

Is that really necessary? 2.3 could have been installed using so many ways, package manager of Linux-distros, SVN, Tarball etc. Seems easier to me to tell people to have a look at the installation instructions.

> The current status of the websvn project; specifically related to this fork and the 2.3.3 version

It's not clear to me what you expect people to say. I have the feeling the project is more about maintenance and keeping WebSVN somewhat alive for existing users.

> For example, changes.txt might reference 2.4 somehow; maybe with a link on top to the 2.4 milestone page?

I've added a note to that file that it's discontinued:

https://github.com/websvnphp/websvn/issues/29

**Comment by ams-tschoening** [comment]
As nobody objected yet, I merged your PR and am closing this issue. Feel free to reopen it or simply provide additional PRs linking here if you think additional changes are necessary. Thanks for contributing!

**Comment by philip** [comment]
@ams-tschoening @michael-o 
The website does not contain this change yet; why not? It appears tied to a 2.5 milestone yet it's a website change. Please consider updating the website, especially considering 2.5 might never exist:

https://websvnphp.github.io/

**Comment by ams-tschoening** [comment]
Which change exactly? Looking at the page, I see all the changes introduced with your PR. The whole `Old Downloads Section` has been introduced by your PR and I see it using the link you provided.

**Comment by philip** [comment]
@ams-tschoening Oh my, please forgive the extra noise I've added here today. Me waiting six months and then adding a comment like this in haste is poor form; yikes! As punishment I'll think of a bug fix or new feature and file a useful PR :)
