### ISSUE TITLE
Add TortoiseSVN url support?

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [websvnphp/websvn#59]
TortoiseSVN can be launched with an url.

https://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-automation-urlhandler.html

Wouldn't it be a nice feature to have a link to TortoiseSVN in the diff page?

**Comment by ams-tschoening** [comment]
And which benefit do you expect exactly? Which link would you like to replace or add?

The only thing coming to my mind currently is browsing the individual differences easier, things like switching between diffing spaces or not etc. OTOH, Tortoise is pretty Windows-specific, so you would clutter the page with very specific links, maybe need to detect the client-OS or need some additional configuration etc. Is that really worth it?

**Comment by michael-o** [comment]
Does this work with Firefox or Chrome?

**Comment by michael-o** [comment]
I also agree with @ams-tschoening.

**Comment by michael-o** [comment]
Can we close this?

**Comment by 0xFEEDC0DE64** [comment]
You can close this, back then when I needed it I added the links in my local copy of websvn.

**Comment by 0xFEEDC0DE64** [comment]
You can close this, back then when I needed it I added the links in my local copy of websvn.

**Comment by ams-tschoening** [comment]
If you already have a working implementation, you might want to consider providing a PR. While that doesn't necessarily mean we merge it, other users might find it interesting and can easily find it if it's linked to this bug.
