### ISSUE TITLE
WebSVN2 with Symfony

### ISSUE THREAD

**Issue by joubertredrat** [websvnphp/websvn#6]
Hi guys, 

If interested, I think that is good idea to create new project and port all features from WebSVN to new version with Symfony support.

Then will more easy to maintain the project.

What you think guys?

**Comment by tschoening** [comment]
At least I have almost no experience with PHP and Symfony, my company doesn't use either of both. So it's very unlikely that I'm able to contribute beyond trivial things. Additionally, starting WebSVN2 while the original one seems almost dead and unmaintained, doesn't make much sense to me. The focus should be to spread the word that here's a (new) project where existing users can contribute their available bugfixes etc. and then see how things are going.

**Comment by joubertredrat** [comment]
Lets refactor actual code then and in future we can return (or not) to this question.
