### ISSUE TITLE
Binary diff/blame/preview handling

### ISSUE THREAD

**Issue by Brightside56** [websvnphp/websvn#60]
Hello. It would great to disable binary files diffs e.t.c. My repo has big binaries and server is dying when someone tries to open changes between revisions. How could I manage this?

**Comment by Brightside56** [comment]
Yes, it displays "cannot display" message but at same time tries to handle this file (websvn from master, latest). I'd like to skip processing of files which shouldn't be touched.

**Comment by ams-tschoening** [comment]
Looking at the code, from my understanding WebSVN does not try to handle files if the quoted message is printed:

	if (!$rep->getIgnoreSvnMimeTypes() && preg_match('~application/*~', $svnMimeType)) {
			$vars['warning'] = 'Cannot display diff of binary file. (svn:mime-type = '.$svnMimeType.')';
		}

https://github.com/websvnphp/websvn/blame/master/diff.php#L134

What it does, though, is reading properties for that file to be able to make a decision at all and that seems the correct thing to do in my opinion:

	// Check for binary file type before diffing.
	$svnMimeType = $svnrep->getProperty($path, 'svn:mime-type', $rev);

https://github.com/websvnphp/websvn/blame/master/diff.php#L131

Seems you need to debug this further, so check which operations and files or dirs exactly stress your servers and afterwards at least if getting the properties is doing that on the shell as well:

    svn proplist [...] --verbose
    svn propget svn:mime-type [...] --verbose

There are some additional repo-accesses before those lines in the file, so if `proplist` is not the problem, you need to debug further and test with the others until the problematic statements are found.

**Comment by michael-o** [comment]
Can we close this?

**Comment by ams-tschoening** [comment]
Agreed, this needs to be debugged further by the reporter and can be reopened in case more info is available.
