### ISSUE TITLE
deprecated class constructors

### ISSUE THREAD

**Issue by Mrten** [websvnphp/websvn#61]
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ParentPath has a deprecated constructor in /var/www/websvn/include/configclass.php on line 102

lots more...

**Comment by joubertredrat** [comment]
which php version are you using?

**Comment by Mrten** [comment]
apologies: 7.0

**Comment by ams-tschoening** [comment]
Are you sure you are talking about the most recent version of WebSVN? Looks to me this specific problem has already been fixed:

https://github.com/websvnphp/websvn/commit/0800bacf2f9264b8707f8084cd4accda62c4fdc0

**Comment by Mrten** [comment]
the latest version from here: https://websvnphp.github.io/download/ : 2.3.3

seems that I should git pull instead? :)

**Comment by ams-tschoening** [comment]
Or one of the newer releases, yes, 2.4 contains the fixes as well.

**Comment by Mrten** [comment]
I am so going to upgrade. Thank you!
Perhaps a reference to that link on the download page?

**Comment by Mrten** [comment]
I think one remains:
```2018-11-28T12:50:16.653118+01:00 websvn php-cgi[2186]: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; BugtraqTestable has a deprecated constructor in /var/www/websvn/include/bugtraq.php on line 224```

**Comment by michael-o** [comment]
@Mrten this should be a separate ticket. Can we close this one?

**Comment by Mrten** [comment]
oh sure, want me to open another one?

**Comment by Mrten** [comment]
(depends on what you mean by "this" though)
