### ISSUE TITLE
svnlook logs passwords

### ISSUE THREAD

**Issue by Mrten** [websvnphp/websvn#62]
it uses error_log which logs passwords from the commandline to syslog (and further if you have remote logging which i do)

from my personal notes:
```
//filter logmessage
function errorlog($string) {
        $string = preg_replace("/--password '.*'/", "--password '***'",$string);
        error_log($string);
}

# en dan met vi :g/error_log/s//errorlog/
# en dan de laatste error_log weer fixen
```

**Comment by ams-tschoening** [comment]
Thanks for reporting! As you can see in the linked PR, we have chosen a slightly different approach, but the result is basically the same.

**Comment by Mrten** [comment]
thanks for fixing, this was a major pain point with 2.3.3 :)

**Comment by Mrten** [comment]
thanks for fixing, this was a major pain point with 2.3.3 :)
