### ISSUE TITLE
Undefined variable: path

### ISSUE THREAD

**Issue by ryanjmulder** [websvnphp/websvn#76]
https://github.com/websvnphp/websvn/blob/aee7f9538ea5ef265c43a77b2e2576e8e44c8be2/include/configclass.php#L590

I'm getting these errors in my Apache error.log

> PHP Notice:  Undefined variable: path in /var/www/websvn/include/configclass.php on line 590

that line is in the function 
`function hasLogReadAccess($pathWithSub)`

should line 590 be using `$pathWithSub` instead of `$path` ?

**Comment by ams-tschoening** [comment]
Thanks for reporting and you are correct.  Please test with the referenced PR as I'm currently unable to do myself because I'm lacking auth on my test-repos.

**Comment by ryanjmulder** [comment]
That causes my errors to clear up, but I'm not sure how to test beyond that.

**Comment by ams-tschoening** [comment]
Should be enough that your messages are gone, so I simply merged.

**Comment by clagio** [comment]
for some reason this fix is not in the 2.5 release.. is correct?

**Comment by ams-tschoening** [comment]
Yes, 2.5 has been released earlier, you need to work with a current master.

> ams-tschoening committed on 1 Apr 2019

vs.

> michael-o released this on 12 Mar 2019
