### ISSUE TITLE
svnauthz path

### ISSUE THREAD

**Issue by trentfisher** [websvnphp/websvn#82]
In my install of Subversion 1.10.4 the svnauthz command is installed to /scm/bin/svn-tools/svnauthz (I built from source with --prefix=/scm).

I was able to kludge my install by making a symlink in /scm/bin (where svn sits), but perhaps the path to that command should be separately configurable (or maybe both paths should be checked), since some may not be able to kludge their install as I could.

**Comment by michael-o** [comment]
I don't understand the problem and this looks wrong:

> In my install of Subversion 1.10.4 the svnauthz command is installed to /scm/bin/svn-tools/svnauthz (I built from source with --prefix=/scm).

I have compiled Subversion many many times myself on many OSes and if your prefix is `/scm` there is no way that the executables will not land in `/scm/bin` unless you provide `--bindir`.

Does `$config->setSVNCommandPath()` not work for you?

**Comment by trentfisher** [comment]
Very strange.  There must be something peculiar about svn 1.10.4.  All the other svn executables end up in /scm/bin, only a handful end up in /scm/bin/svn-tools.  The makefile explicitly does this:

```
toolsdir = ${exec_prefix}/bin/svn-tools
...
install-tools:
...
        cd tools/server-side ; $(INSTALL_TOOLS) svnauthz$(EXEEXT) $(DESTDIR)$(toolsdir)/svnauthz$(EXEEXT)
```

I would be tempted to just redefine "toolsdir" when I build, but there are some things in that directory which would be a problem in /bin (notably "diff").

setSvnCommandPath is only for the "svn" command.  Perhaps we need a setSvnAuthzCommand to match getSvnAuthzCommand.  I'll add that if there are no objections.

**Comment by michael-o** [comment]
This sucks.  I can confirm this on HP-UX. I have installed 1.10.4 to `/opt/ports` and cannot find `svnauthz` anywhere. `toolsdir` isn't mentioned in `./configure --help`. According to the logs, it has been like this forever. One as to perform `make tools && make install-tools` to have them installed. 

And here is the reason why it always worked for me on our FreeBSD server: https://github.com/freebsd/freebsd-ports/blob/master/devel/subversion-lts/files/patch-Makefile.in, as well as https://github.com/freebsd/freebsd-ports/blob/master/devel/subversion-lts/Makefile#L153-L154 and https://github.com/freebsd/freebsd-ports/blob/master/devel/subversion-lts/Makefile#L169-L171.

Changing `toolsdir` with the make invocation would be actually a good solution, but I think your doubts are justified.

You are probably right, this needs to be fixed. You probably mean: `setSvnAuthzCommandPath`.

**Comment by krischik** [comment]
I have no svnauthz:

```
>la /var/packages/SVN/target/bin/*
-rwxr-xr-x 1 root root 1,1M Aug 16  2017 /var/packages/SVN/target/bin/svn*
-rwxr-xr-x 1 root root 187K Aug 16  2017 /var/packages/SVN/target/bin/svnadmin*
-rwxr-xr-x 1 root root 197K Aug 16  2017 /var/packages/SVN/target/bin/svnbench*
-rwxr-xr-x 1 root root  94K Aug 16  2017 /var/packages/SVN/target/bin/svndumpfilter*
-rwxr-xr-x 1 root root 103K Aug 16  2017 /var/packages/SVN/target/bin/svnfsfs*
-rwxr-xr-x 1 root root 162K Aug 16  2017 /var/packages/SVN/target/bin/svnlook*
-rwxr-xr-x 1 root root  72K Aug 16  2017 /var/packages/SVN/target/bin/svnmucc*
-rwxr-xr-x 1 root root 172K Aug 16  2017 /var/packages/SVN/target/bin/svnrdump*
-rwxr-xr-x 1 root root 304K Aug 16  2017 /var/packages/SVN/target/bin/svnserve*
-rwxr-xr-x 1 root root 154K Aug 16  2017 /var/packages/SVN/target/bin/svnsync*
-rwxr-xr-x 1 root root  45K Aug 16  2017 /var/packages/SVN/target/bin/svnversion*
```

Is that some new feature? And if so: with what version of websvn was it introduced. Easier for me to install an older websvn than updating svn.

**Comment by michael-o** [comment]
@krischik Something is wrong with your installation then. Recompile and reinstall and it will be there.

**Comment by ams-tschoening** [comment]
> Is that some new feature? And if so: with what version of websvn was it introduced. Easier for me to install an older websvn than updating svn.

This change has been introduced with the first new release, 2.4:

https://github.com/websvnphp/websvn/releases/tag/2.4
https://github.com/websvnphp/websvn/milestone/1?closed=1
https://github.com/websvnphp/websvn/pull/37

**Comment by krischik** [comment]
@ams-tschoening Thanks. I installed 1.3.2 and that worked fine.
