### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by ghost** [websvnphp/websvn#83]
Hi, thanks for the great work on this.  Are there any future plans for adding markdown rendering?  Your project is giving us everything we need except for that, and we just noticed that VIsualSVN implemented a "homepage" similar to the GitHub homepage (displaying readme markdown) when browsing to the project trunk.

I may end up taking a stab at this if there were no plans for it.

Also, this project is still being maintained?  I saw a comment in one of the other issues threads when talking about WebSVN2 that the original project is dead.  Was that referring to this project?

Thanks again!

**Comment by ams-tschoening** [comment]
> Are there any future plans for adding markdown rendering?

None I'm aware of.

> Also, this project is still being maintained?

At least some issues are dealt with. If that is enough for anyone needs to be decided by oneself. But if I was you I wouldn't expect too much to happen unless people of interest like you have are doing it.

**Comment by michael-o** [comment]
What do you mean by homepage? You can put a README.xy in your repo and that should serve the purpose. I do not really want to extend to more than source code browsing because someone else will ask for Asciidoc support, bla bla support.

Please provide a concrete idea for your request.

**Comment by perryjohnson01** [comment]
I guess the best way to describe is to have a look at the VisualSVN demo?  Basically they are copying from GitHub, the project "homepage".  So when viewing a directory with a readme.md file in it, it auto displays at the bottom as html with a markdown renderer
[Main Page](https://demo-server.visualsvn.com/!/#)
[Webkit Demo Homepage](https://demo-server.visualsvn.com/!/#webkit/view/head/trunk)

**Comment by michael-o** [comment]
OK, pretty much like with GitHub/GitLab. The problem now with Markdown that there is "the" Markdown, there tens of flavors...

**Comment by spmeesseman** [comment]
I've completed a markdown support version of websvn that works like VisualSVN and GitHub.  See my forked version, the "websvn-spm" branch (the master branch i intend to keep in sync with this repo).  Support made possible by parsedown and parsedown-toc modules

**Comment by ams-tschoening** [comment]
@spmeesseman Thanks for the work and I suggest you provide your changes as PR, so we can discuss and review things more concrete. I've spotted some minor things which need to be improved before merging in my opinion:

* redundant code around `pathinfo` -> some function
* `tmpfile` breaks most likely in case of concurrent requests -> random file
* embedding `parsedown` vs. using `PEAR`
* Rendering always vs. raw rendering, Github allows switching between both. Some way to opt-in/opt-out from rendering?

**Comment by kirbyzhou** [comment]
> I've completed a markdown support version of websvn that works like VisualSVN and GitHub. See my forked version, the "websvn-spm" branch (the master branch i intend to keep in sync with this repo). Support made possible by parsedown and parsedown-toc modules. Note it looks best when setting websvn to 'flat' view instead of the default 'tree'

Could you please list your git repo url here?
I want to try it.

**Comment by tchule** [comment]
+1, would be really interested in having a Markdown renderer.

Thx.

**Comment by ams-tschoening** [comment]
The repo in question is the following:

https://github.com/spmeesseman/websvn
