### ISSUE TITLE
Support one WebSVN-installation hosting multiple parent paths to SVN-repos.

### ISSUE THREAD

**Issue by ams-tschoening** [websvnphp/websvn#86]
# My background.

In the past, my SVN repos where organized pretty flat, all in one directory and that has been published by `svnserve`. I recently refactored this to allow multiple subdirs to divide things by customers or some topic etc., which is easily supported by `svnserve`, because it maps all relative URLs to repos into its one and only configured root path. That is different for mod_dav_svn and WebSVN, the latter being more difficult, though.

# Multiple config files necessary.

From my understanding, WebSVN only loads repos somehow known to `config.php`, either being directly configured or using a parent path, pretty much like `svnserve` supports. The difference is that WebSVN ignores all non-repos in the configured parent path, so one needs to configure multiple parent paths and that leads to another problem: Each parent path needs its own `config.php` and that is assumed under a hard-coded path by WebSVN to be included. So one not only needs to maintain multiple `config.php` currently, but as well one installation of WebSVN.

In this issue I would like to discuss alternatives, especially because additional subdirs might provide [performance benefits](https://github.com/websvnphp/websvn/issues/78), as fewer repos need to be checked for if the current user has access to those.

# Configurable path to config file.

The first problem to solve is that WebSVN doesn't assume [one config file in its own installation directory](https://github.com/websvnphp/websvn/blob/master/include/setup.php#L321) anymore by convention. That assumption forces one to need multiple installations of WebSVN in worst case.

The workaround I'm currently implementing for that problem is simply setting environment variables based on the requested location in Apache httpd. The requested location reflects the relative dir structure of my repos, corresponds to a lot of `Location` blocks in `httpd` and ultimately things are mapped to one environment variable containing a path to `config.php`.

While the many `Location` blocks are some maintenance overhead as well, one doesn't need to additionally maintain individual WebSVN-installations. Besides that, all those blocks allow individual handling of things like authentication, different realms and stuff. I for example implemented a custom auth-handler using mod_perl, reusing passwd-files for all individual repos and stuff.

The following is a PR implementing my approach and containing example configs for `httpd`:

https://github.com/websvnphp/websvn/pull/87

# Layered configs.

The downside of the former approach is that for each parent path with SVN-repos an individual `config.php` is necessary, making configs for templates, paths to tools etc. redundant. In most cases it's pretty likely in my opinion that all repos should be presented the same way, so share a lot of configs.

Because configs are only PHP-code setting properties, it should be easy to layer them by simply processing one after another following some convention. E.g. my current implementation either uses the conventional environment variable or `config.php` the old way, but could as well easily use one after the other.

# Discussion.

What's your opinions? Do you have a similar use case and if so, how do you deal with it?

**Comment by michael-o** [comment]
I understand the usecase, but I think that WebSVN should reflect the options provided by `mod_dav_svn` which obviously does not support nesting.

**Comment by michael-o** [comment]
Can't you achieve your layered design by have a `config.include.php` and require this in your specific `config.php`s?

**Comment by michael-o** [comment]
Accepted.

**Comment by ams-tschoening** [comment]
Leaving this open until https://github.com/websvnphp/websvnphp.github.io/pull/4 is merged, so we don't miss that. Besides that, the current implementation is enough for a starting point, everything more complex should get new issues with concrete examples of what is needed why.
