### ISSUE TITLE
path not visible anymore since 2.4

### ISSUE THREAD

**Issue by neeral85** [websvnphp/websvn#88]
since version 2.4 it's not possible anymore to see folders with dedicate access but no access to root folder

example:

### svn-tree:
branches/ 
tags/
trunk/
trunk/folder1
trunk/folder1/folder_a

### apache.authz
[groups]
admin= admin
user= user

[/]
*=
@admin=rw

[/trunk]
@user=rw

[/trunk/folder1/]
user2=r

### Issue
user 2 can't see `/trunk/folder1/folder_a/` or even `/trunk/folder1`
even if you provide &path variable to url pointing to `/trunk/folder1/` you won't be able to see content of this path in WebSVN

 
[properly related to this](https://github.com/websvnphp/websvn/pull/37)

**Comment by ams-tschoening** [comment]
This is the same problem like #85 and therefore I'm closing this issue. Let's keep discussion in the formerly created one for now.
